Bill xiong
SpotifySugg4/spotsugfe pull request #3
Opened 2020-10-19 02:44 UTC by bxiong916

2020-10-19 03:26 UTC, kevinstonge requested changes
please do not merge.

this pull request should only include Login.js and Register.js

either remove the other files from the commit or restore them to match what is in the main branch.

thank you

2020-10-20 01:40 UTC, tippitytapp requested changes
need to remove try unclanged files

2020-10-20 01:55 UTC, tippitytapp approved these changes

2020-10-20 02:00 UTC, tippitytapp approved these changes
Bill please reclone and npm i the repo

2020-10-20 02:07 UTC, merged